version: 2

sources:
  - name: source_platform_commons
    schema: pc_staging
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: user_data_int
        identifier: User_DATA_v2
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: applicant_data_2023_int
        identifier: Applicant_Data_2023
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: applicant_data_2024_int
        identifier: Applicant_Data_2024
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: applicant_data_2025_int
        identifier: Applicant_Data_2025
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: child_attendance_int
        identifier: Child_Attendence
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: class_ops_master_data_int
        identifier: Class_ops_master_data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: credit_data_int
        identifier: Credit_Data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: events_data_int
        identifier: Events_Data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: fellow_applicant_data_int
        identifier: Fellow_Applicant_Data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: fundraising_donations_int
        identifier: Fundraising_Donations
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: students_data_int
        identifier: Students_Data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: school_id_int
        identifier: School_IDs
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: target_settings_int
        identifier: Target_Setting_
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at
      - name: volunteer_retention_d_int
        identifier: Volunteer_Retention_Data
        description: Platform common api
        loaded_at_field: _airbyte_extracted_at

  - name: crm_data
    schema: crm_staging
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: pocs
        identifier: pocs
        description: CRM points of contact data
        loaded_at_field: _airbyte_extracted_at
      - name: mous
        identifier: mous
        description: CRM Memorandum of Understanding data
        loaded_at_field: _airbyte_extracted_at
      - name: cities
        identifier: cities
        description: CRM cities master data
        loaded_at_field: _airbyte_extracted_at
      - name: states
        identifier: states
        description: CRM states master data
        loaded_at_field: _airbyte_extracted_at
      - name: partner_agreements
        identifier: partner_agreements
        description: CRM partner agreements and contracts
        loaded_at_field: _airbyte_extracted_at
      - name: poc_partners
        identifier: poc_partners
        description: CRM point of contact and partner relationships
        loaded_at_field: _airbyte_extracted_at
      - name: manager_co
        identifier: manager_co
        description: CRM manager and company relationships
        loaded_at_field: _airbyte_extracted_at
      - name: partners
        identifier: partners
        description: CRM partners master data
        loaded_at_field: _airbyte_extracted_at
      - name: partner_cos
        identifier: partner_cos
        description: CRM partner company relationships
        loaded_at_field: _airbyte_extracted_at
      - name: meetings
        identifier: meetings
        description: CRM meetings and interactions data
        loaded_at_field: _airbyte_extracted_at

  - name: google_sheet_staging
    schema: google_sheet_staging
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: e1_e2_co_mapping
        identifier: e1_e2_co_mapping
        description: Google sheet E1 E2 CO mapping data
        loaded_at_field: _airbyte_extracted_at
      - name: e1_cci_chapter_mapping
        identifier: e1_cci_chapter_mapping
        description: Google sheet E1 CCI chapter mapping data
        loaded_at_field: _airbyte_extracted_at

  - name: bubble_staging
    schema: bubble_staging
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: partner
        identifier: partner
        description: Bubble partner master data 
        loaded_at_field: _airbyte_extracted_at
      - name: user
        identifier: user
        description: Bubble user master data
        loaded_at_field: _airbyte_extracted_at
      - name: batch_child
        identifier: batch_child
        description: Bubble batch and child relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: chapter
        identifier: chapter
        description: Bubble chapter master data
        loaded_at_field: _airbyte_extracted_at
      - name: chapter_school
        identifier: chapter_school
        description: Bubble chapter and school relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: child
        identifier: child
        description: Bubble child master data
        loaded_at_field: _airbyte_extracted_at
      - name: child_class
        identifier: child_class
        description: Bubble child and class relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: child_class_section
        identifier: child_class_section
        description: Bubble child and class section relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: child_program
        identifier: child_program
        description: Bubble child and program relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: child_subject
        identifier: child_subject
        description: Bubble child and subject relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: class
        identifier: class
        description: Bubble class master data
        loaded_at_field: _airbyte_extracted_at
      - name: class_section
        identifier: class_section
        description: Bubble class section data
        loaded_at_field: _airbyte_extracted_at
      - name: class_section_subject
        identifier: class_section_subject
        description: Bubble class section and subject relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: co_chapter
        identifier: co_chapter
        description: Bubble co-chapter program data
        loaded_at_field: _airbyte_extracted_at
      - name: program
        identifier: program
        description: Bubble program master data
        loaded_at_field: _airbyte_extracted_at
      - name: school_class
        identifier: school_class
        description: Bubble school and class relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: school_volunteer
        identifier: school_volunteer
        description: Bubble school and volunteer relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: slot
        identifier: slot
        description: Bubble time slot data
        loaded_at_field: _airbyte_extracted_at
      - name: slot_class_section
        identifier: slot_class_section
        description: Bubble slot and class section relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: slot_class_section_volunteer
        identifier: slot_class_section_volunteer
        description: Bubble slot, class section and volunteer relationship data
        loaded_at_field: _airbyte_extracted_at
      - name: subject
        identifier: subject
        description: Bubble subject master data
        loaded_at_field: _airbyte_extracted_at
      - name: child_removal_log
        identifier: child_removal_log
        description: Bubble child removal log data
        loaded_at_field: _airbyte_extracted_at

models:
  - name: school_data_comparison
    description: Comprehensive view of all schools with CO details and child count metrics. Includes schools from CRM (with converted agreements) and schools only in Bubble system.
    columns:
      - name: "Partner ID"
        description: Unique identifier for the partner (CRM ID for CRM schools, Bubble ID for Bubble-only schools)
      - name: "Partner Name"
        description: Name of the partner organization
      - name: "CO ID"
        description: User ID of the Community Organizer who created the partner
      - name: "CO Name"
        description: Display name of the Community Organizer
      - name: "MOU Sign Date"
        description: Date when the MOU was signed
      - name: "Weeks Since MOU Signed"
        description: Number of weeks elapsed since the MOU was signed (calculated as floor of days difference divided by 7)
      - name: "Confirmed Child Count (CRM)"
        description: Number of children confirmed in CRM (from partner agreements)
      - name: "Active Child Count (Bubble)"
        description: Number of active children in Bubble system
      - name: "Dropped Child Count (Bubble)"
        description: Number of dropped/inactive children in Bubble system
      - name: "Platform Presence"
        description: Platform presence of the school - 'BOTH' for schools in both CRM and Bubble, 'CRM' for schools only in CRM, 'BUBBLE' for schools only in Bubble
      - name: "CRM Status"
        description: Numeric indicator for CRM presence - 100 for schools in CRM (CRM or BOTH), 0 for Bubble-only schools
      - name: "Child Count Ratio (Bubble / CRM)"
        description: Percentage ratio of active children in Bubble divided by confirmed children in CRM, multiplied by 100. Values > 100 indicate Bubble has more children, < 100 indicate fewer, = 100 indicates perfect match. NULL for schools without CRM data.

  - name: volunteer_recruitment_data
    description: Volunteer recruitment data with partner details, CO information, child counts, and volunteer metrics including recruitment targets and assignments
    columns:
      - name: partner_id
        description: Unique identifier for the partner organization (NULL for unassigned volunteers)
      - name: partner_name
        description: Name of the partner organization ('Unassigned' for volunteers not yet assigned to any school)
      - name: co_id
        description: User ID of the Community Organizer who created the partner
      - name: co_name
        description: Display name of the Community Organizer
      - name: active_child_count
        description: Number of active children enrolled at this partner/school from Bubble system
      - name: volunteers_required
        description: Calculated number of volunteers required (4/5 times the active child count)
      - name: volunteers_assigned_to_school
        description: Number of volunteers assigned to this specific school (for unassigned rows, shows count of unassigned volunteers)
      - name: volunteers_assigned_to_class
        description: Number of volunteers assigned to classes at this school (through slot assignments)

    
